Write-Host "================================================"
Write-Host "QUALIFY.AI - DATA SETUP COMPLETE!"
Write-Host "================================================"
Write-Host ""
Write-Host "Data Location: D:\allure-reports\13-11-2025\"
Write-Host "Total Files: 32 JSON files"
Write-Host ""
Write-Host "Dashboard: http://localhost:3000/dashboard"
Write-Host ""
Write-Host "TO USE YOUR REAL DATA:"
Write-Host "1. Open http://localhost:3000/dashboard"
Write-Host "2. Click 'Upload Allure Report'"  
Write-Host "3. Select folder D:\allure-reports\13-11-2025"
Write-Host "4. Dashboard will show your 32 real tests!"
Write-Host ""
Write-Host "See: HƯỚNG_DẪN_SỬ_DỤNG_DATA_THẬT.md for details"
Write-Host "================================================"

